"""Immutable presentation-ready models shared by future interfaces."""

from __future__ import annotations

from dataclasses import dataclass
from enum import Enum
from typing import Any


class WarningCode(str, Enum):
    """Stable structured warning identifiers."""

    ARTIFICIAL_BASELINE_INCLUDED = "artificial_zero_baseline_included"
    FRAME_LABELS_AUTOGENERATED = "frame_labels_autogenerated"
    TIME_VALUES_AUTOGENERATED = "time_values_autogenerated"
    EMPTY_SIGNAL_ALL_FRAMES = "empty_signal_all_frames"
    CHANNEL_HAS_NO_SIGNAL = "selected_channel_has_no_signal"
    NON_MONOTONIC_TIME = "non_monotonic_time_values"
    DTYPE_RANGE_MISMATCH = "dtype_range_threshold_mismatch"
    PARTIAL_RESULT = "partial_result"


@dataclass(frozen=True)
class WarningRecord:
    """User-facing warning with stable code and remediation."""

    code: WarningCode
    message: str
    detail: str
    field: str | None = None
    remediation: str | None = None


@dataclass(frozen=True)
class ChannelAccumulationSeries:
    """One selected channel's legacy-compatible baseline series."""

    channel: str
    threshold: float
    signal_pixels: tuple[float, ...]
    area_micrometres_squared: tuple[float, ...]
    accumulation_pixels: tuple[float, ...]
    accumulation_micrometres_squared: tuple[float, ...]


@dataclass(frozen=True)
class Provenance:
    """Non-identifying reproducibility metadata."""

    workflow_name: str
    workflow_contract_version: str
    application_version: str
    scientific_core_module: str
    channel_convention: str
    selected_channels: tuple[str, ...]
    thresholds: tuple[tuple[str, float], ...]
    micrometres_per_pixel: float
    frame_count: int
    time_convention: str
    artificial_baseline_convention: str
    source_identifiers: tuple[str, ...]
    metadata: tuple[tuple[str, str], ...]
    warning_codes: tuple[str, ...]


@dataclass(frozen=True)
class ROIAccumulationResult:
    """Complete application-facing ROI accumulation result."""

    workflow_id: str
    contract_version: str
    frame_labels: tuple[str, ...]
    time_values: tuple[float, ...]
    channels: tuple[ChannelAccumulationSeries, ...]
    units: tuple[tuple[str, str], ...]
    parameters: tuple[tuple[str, Any], ...]
    warnings: tuple[WarningRecord, ...]
    provenance: Provenance
    suggested_export_stem: str


@dataclass(frozen=True)
class TableData:
    """Table-ready columns and immutable row tuples."""

    columns: tuple[str, ...]
    rows: tuple[tuple[Any, ...], ...]


@dataclass(frozen=True)
class PlotSeries:
    """Named x/y data without a plotting-library dependency."""

    name: str
    channel: str
    quantity: str
    x: tuple[float, ...]
    y: tuple[float, ...]
    x_unit: str
    y_unit: str
