"""Phase 3A ROI request validation and normalization tests."""

from __future__ import annotations

import dataclasses

import numpy as np
import pytest

from iclotspython.application.contracts import (
    ChannelConvention,
    ColorChannel,
    ROIAccumulationRequest,
    WorkflowMetadata,
)
from iclotspython.application.errors import (
    RequestValidationError,
    UnsupportedInputShapeError,
)
from iclotspython.application.validation import (
    validate_roi_accumulation_request,
)
from iclotspython.presentation.models import WarningCode


pytestmark = pytest.mark.unit


def _frame(value: int = 0) -> np.ndarray:
    return np.full((2, 3, 3), value, dtype=np.uint8)


def _request(**changes) -> ROIAccumulationRequest:
    values = {
        "frames": (_frame(), _frame(10)),
        "selected_channels": (ColorChannel.RED,),
        "thresholds": {ColorChannel.RED: 5},
        "micrometres_per_pixel": 0.5,
        "channel_convention": ChannelConvention.BGR,
        "frame_labels": ("first", "second"),
        "time_values": (1.0, 2.0),
    }
    values.update(changes)
    return ROIAccumulationRequest(**values)


def test_valid_request_is_normalized_to_read_only_private_arrays():
    original = _frame(7)
    outcome = validate_roi_accumulation_request(
        _request(frames=(original, _frame(8)))
    )
    original[:] = 99
    assert outcome.request.frames[0][0, 0, 0] == 7
    assert not outcome.request.frames[0].flags.writeable
    assert outcome.request.threshold_for(ColorChannel.RED) == 5
    with pytest.raises(ValueError):
        outcome.request.frames[0][0, 0, 0] = 1


def test_request_contract_is_frozen():
    request = _request()
    with pytest.raises(dataclasses.FrozenInstanceError):
        request.micrometres_per_pixel = 2


def test_no_frames_is_invalid():
    with pytest.raises(RequestValidationError, match="At least one frame") as exc:
        validate_roi_accumulation_request(_request(frames=()))
    assert exc.value.code == "no_frames"


@pytest.mark.parametrize(
    "frames",
    [
        (np.zeros((2, 3), dtype=np.uint8),),
        (_frame(), np.zeros((3, 3, 3), dtype=np.uint8)),
        (np.zeros((2, 3, 4), dtype=np.uint8),),
    ],
)
def test_unsupported_or_inconsistent_dimensions_are_rejected(frames):
    with pytest.raises(UnsupportedInputShapeError):
        validate_roi_accumulation_request(_request(frames=frames))


def test_missing_selected_channel_threshold_is_invalid():
    with pytest.raises(RequestValidationError) as exc:
        validate_roi_accumulation_request(_request(thresholds={}))
    assert exc.value.code == "missing_selected_channel_threshold"


@pytest.mark.parametrize("threshold", [np.nan, np.inf, -1, 256])
def test_invalid_threshold_is_rejected(threshold):
    with pytest.raises(RequestValidationError) as exc:
        validate_roi_accumulation_request(
            _request(thresholds={ColorChannel.RED: threshold})
        )
    assert exc.value.code in {"invalid_threshold", "threshold_outside_dtype_range"}


@pytest.mark.parametrize("calibration", [0, -0.5, np.nan, np.inf])
def test_nonpositive_or_nonfinite_calibration_is_rejected(calibration):
    with pytest.raises(RequestValidationError) as exc:
        validate_roi_accumulation_request(
            _request(micrometres_per_pixel=calibration)
        )
    assert exc.value.code == "invalid_calibration"


def test_incorrect_label_and_time_counts_are_rejected():
    with pytest.raises(RequestValidationError) as label_error:
        validate_roi_accumulation_request(_request(frame_labels=("only",)))
    assert label_error.value.code == "incorrect_frame_label_count"
    with pytest.raises(RequestValidationError) as time_error:
        validate_roi_accumulation_request(_request(time_values=(1.0,)))
    assert time_error.value.code == "incorrect_time_value_count"


def test_nonfinite_time_is_rejected():
    with pytest.raises(RequestValidationError) as exc:
        validate_roi_accumulation_request(_request(time_values=(1.0, np.nan)))
    assert exc.value.code == "non_finite_time_values"


@pytest.mark.parametrize("convention", [None, "", "GRB"])
def test_ambiguous_channel_convention_is_rejected(convention):
    with pytest.raises(RequestValidationError) as exc:
        validate_roi_accumulation_request(
            _request(channel_convention=convention)
        )
    assert exc.value.code == "ambiguous_channel_convention"


def test_unsupported_selected_channel_is_rejected():
    with pytest.raises(RequestValidationError) as exc:
        validate_roi_accumulation_request(
            _request(selected_channels=("infrared",))
        )
    assert exc.value.code == "unsupported_selected_channel"


def test_autogenerated_labels_times_and_nonmonotonic_warning_are_structured():
    generated = validate_roi_accumulation_request(
        _request(frame_labels=None, time_values=None)
    )
    assert generated.request.frame_labels == ("frame_0001", "frame_0002")
    assert generated.request.time_values == (1.0, 2.0)
    generated_codes = {warning.code for warning in generated.warnings}
    assert WarningCode.FRAME_LABELS_AUTOGENERATED in generated_codes
    assert WarningCode.TIME_VALUES_AUTOGENERATED in generated_codes

    nonmonotonic = validate_roi_accumulation_request(
        _request(time_values=(2.0, 1.0))
    )
    assert WarningCode.NON_MONOTONIC_TIME in {
        warning.code for warning in nonmonotonic.warnings
    }


def test_source_identifiers_must_match_frame_count_when_supplied():
    with pytest.raises(RequestValidationError) as exc:
        validate_roi_accumulation_request(
            _request(metadata=WorkflowMetadata(source_identifiers=("one",)))
        )
    assert exc.value.code == "incorrect_source_identifier_count"

